const payloadFields = [
  'load_id',
  'gps',
  'timestamp',
  'selfie_hash',
  'facility_hash',
];

const proofs = [
  {
    title: 'Authenticity',
    description: 'This PDF was generated by FreightPassport, not Photoshop.',
    icon: <ShieldCheck />,
  },
  {
    title: 'Integrity',
    description: 'No field has been modified since signing.',
    icon: <Lock />,
  },
  {
    title: 'Binding',
    description:
      'This signature is valid for exactly one load — cannot be ported.',
    icon: <Chain />,
  },
  {
    title: 'Provenance',
    description:
      'GPS, timestamp, and signer identity are all in the signed payload.',
    icon: <Pin />,
  },
];

export default function CryptoDeepDive() {
  return (
    <section
      id="crypto-deep-dive"
      className="border-t border-border py-28 md:py-36"
      aria-labelledby="crypto-heading"
    >
      <div className="max-w-6xl mx-auto px-6">
        {/* ── Part 1: How signing works ── */}
        <span className="eyebrow">Cryptographic model</span>

        <h2
          id="crypto-heading"
          className="mt-6 text-4xl md:text-5xl font-extrabold tracking-tight leading-[1.05] text-ink"
        >
          Every document is mathematically&nbsp;unforgeable.
        </h2>

        <div className="mt-14 grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16">
          {/* Left — explanation */}
          <div className="flex flex-col justify-center">
            <p className="text-base md:text-lg text-ink-muted leading-relaxed">
              When a driver taps &ldquo;Confirm Pickup,&rdquo; FreightPassport
              assembles every piece of context — GPS coordinates, timestamp,
              biometric selfie hash, facility photo hash, and the load&nbsp;ID —
              into a single payload.
            </p>
            <p className="mt-5 text-base md:text-lg text-ink-muted leading-relaxed">
              That payload is signed <strong className="text-ink">twice</strong>:
              once with a per-load ephemeral key (proving this driver, this load)
              and again with the platform key (proving FreightPassport witnessed
              it). Both signatures are embedded directly in the BOL/POD PDF, so
              any third party can verify authenticity without calling
              our&nbsp;API.
            </p>
            <p className="mt-5 text-base md:text-lg text-ink-muted leading-relaxed">
              The result: a document that is cryptographically impossible to
              forge, modify, or transplant between&nbsp;loads.
            </p>
          </div>

          {/* Right — signing flow diagram */}
          <div className="flex flex-col items-center gap-0">
            {/* Card 1: Payload assembled */}
            <div className="bg-navy rounded-2xl p-6 w-full">
              <p className="text-[11px] font-mono uppercase tracking-widest text-white/60 mb-4">
                Payload assembled
              </p>
              <ul className="space-y-2">
                {payloadFields.map((field) => (
                  <li key={field} className="flex items-center gap-2.5">
                    <GreenCheck />
                    <span className="font-mono text-[11px] text-white/90">
                      {field}
                    </span>
                  </li>
                ))}
              </ul>
            </div>

            <DownArrow />

            {/* Card 2: Double signed */}
            <div className="card p-6 w-full">
              <p className="text-[11px] font-mono uppercase tracking-widest text-ink-muted mb-4">
                Double signed
              </p>
              <div className="space-y-3">
                <div className="flex flex-wrap items-center gap-2 text-[13px] text-ink-muted">
                  <span className="font-semibold text-ink">Per-load key</span>
                  <Chevron />
                  <span className="font-mono text-[11px]">
                    Ed25519.sign(payload)
                  </span>
                  <Chevron />
                  <span className="chip">load_signature</span>
                </div>
                <div className="flex flex-wrap items-center gap-2 text-[13px] text-ink-muted">
                  <span className="font-semibold text-ink">Platform key</span>
                  <Chevron />
                  <span className="font-mono text-[11px]">
                    Ed25519.sign(payload&nbsp;+&nbsp;load_sig)
                  </span>
                  <Chevron />
                  <span className="chip">platform_signature</span>
                </div>
              </div>
            </div>

            <DownArrow />

            {/* Card 3: Embedded in PDF */}
            <div className="card-shadow p-6 w-full">
              <div className="flex items-center gap-3 mb-4">
                <DocIcon />
                <p className="text-[11px] font-mono uppercase tracking-widest text-ink-muted">
                  Embedded in PDF
                </p>
              </div>
              <p className="font-semibold text-ink mb-3">BOL / POD PDF</p>
              <ul className="space-y-2 text-sm text-ink-muted">
                <li className="flex items-start gap-2">
                  <GreenCheck />
                  <span>Both signatures embedded via pyhanko</span>
                </li>
                <li className="flex items-start gap-2">
                  <GreenCheck />
                  <span>
                    Verification QR code links to public&nbsp;verifier
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <GreenCheck />
                  <span>
                    Platform public key published at{' '}
                    <code className="font-mono text-[11px] text-accent">
                      .well-known/
                    </code>
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* ── Part 2: What cryptography proves ── */}
        <hr className="hairline my-20" />

        <h2 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-[1.05] text-ink">
          What cryptography&nbsp;proves
        </h2>

        <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {proofs.map((p) => (
            <div key={p.title} className="card-shadow p-6">
              <div className="mb-4">{p.icon}</div>
              <h3 className="text-xl md:text-2xl font-bold text-ink">
                {p.title}
              </h3>
              <p className="mt-2 text-base md:text-lg text-ink-muted">
                {p.description}
              </p>
            </div>
          ))}
        </div>

        {/* ── Part 3: What it does NOT prove ── */}
        <div className="mt-16 bg-warning-wash border border-[var(--color-warning)] rounded-2xl p-6 md:p-8">
          <h3 className="text-xl md:text-2xl font-bold text-ink">
            What cryptography alone does NOT&nbsp;prove
          </h3>
          <p className="mt-3 text-base md:text-lg text-ink-muted leading-relaxed">
            That the human at the keyboard is who they claim to be. A perfectly
            signed load from a fake broker is still fraud with a signature. This
            is why identity verification (Bronze / Silver / Gold tiers) precedes
            every cryptographic&nbsp;operation.
          </p>
          <a
            href="#identity-tiers"
            className="mt-5 inline-flex items-center gap-1.5 text-accent font-semibold hover:underline"
          >
            See Identity Tiers below&ensp;&darr;
          </a>
        </div>
      </div>
    </section>
  );
}

/* ─── Icons ─── */

function GreenCheck() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      className="flex-shrink-0"
      aria-hidden="true"
    >
      <path
        d="M5 13l4 4L19 7"
        stroke="#22c55e"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function DownArrow() {
  return (
    <div className="py-2" aria-hidden="true">
      <svg width="20" height="28" viewBox="0 0 20 28" fill="none">
        <path
          d="M10 2v20m0 0l-6-6m6 6l6-6"
          stroke="var(--color-accent)"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </div>
  );
}

function Chevron() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      className="text-ink-subtle flex-shrink-0"
      aria-hidden="true"
    >
      <path
        d="M9 6l6 6-6 6"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function DocIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M14 2v6h6M16 13H8M16 17H8M10 9H8"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ShieldCheck() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M12 2l7 4v5c0 5.25-3.5 9.74-7 11-3.5-1.26-7-5.75-7-11V6l7-4z"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M9 12l2 2 4-4"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function Lock() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <rect
        x="3"
        y="11"
        width="18"
        height="11"
        rx="2"
        stroke="#0B5FFF"
        strokeWidth="2"
      />
      <path
        d="M7 11V7a5 5 0 0110 0v4"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </svg>
  );
}

function Chain() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"
        stroke="#0B5FFF"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function Pin() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z"
        stroke="#0B5FFF"
        strokeWidth="2"
      />
      <circle cx="12" cy="9" r="2.5" stroke="#0B5FFF" strokeWidth="2" />
    </svg>
  );
}
